"""Scraper service: fetch, parse, and upsert reviews from GitHub Pages.

Review repos are prefixed with "review-" in the ParallelScience org.
The GitHub Pages site uses the OpenReview-style template generated by
build_review_page.py in denario-scientists/tools/.
"""

import hashlib
import json
import logging
import os
import re
import sqlite3
import sys
from html.parser import HTMLParser

from review_browse.services.id_registry import get_or_assign_review_id

log = logging.getLogger(__name__)

GCS_BUCKET = "parallel-review"


# ---------------------------------------------------------------------------
# HTML parser for review GitHub Pages sites
# ---------------------------------------------------------------------------

class ReviewPageParser(HTMLParser):
    """Extract paper title, author, date from a review GitHub Pages site.

    The page template uses OpenReview-style classes:
      <div class="forum-title"><h2>Title</h2></div>
      <div class="forum-authors">Author</div>
      <div class="forum-meta"><span>date</span><span>time</span>...</div>
    And navbar links to the paper's Pages URL.
    """

    def __init__(self):
        super().__init__()
        self._in_tag = None
        self._in_class = None
        self._current_text = []

        self.title = ""
        self.author = ""
        self.date = ""
        self.time = ""
        self.paper_pages_url = ""

    def handle_starttag(self, tag, attrs):
        attrs_dict = dict(attrs)
        cls = attrs_dict.get("class", "")

        # Title: <h2> inside .forum-title
        if tag == "div" and "forum-title" in cls:
            self._in_class = "forum-title"
        elif tag == "h2" and self._in_class == "forum-title":
            self._in_tag = "title"
            self._current_text = []

        # Author: .forum-authors div
        elif tag == "div" and "forum-authors" in cls:
            self._in_tag = "authors"
            self._current_text = []

        # Meta bar: .forum-meta with <span> children
        elif tag == "div" and "forum-meta" in cls:
            self._in_class = "forum-meta"
        elif tag == "span" and self._in_class == "forum-meta":
            self._in_tag = "meta-span"
            self._current_text = []

        # Paper link in navbar
        elif tag == "a":
            href = attrs_dict.get("href", "")
            if "parallelscience.github.io" in href and "review" not in href:
                self.paper_pages_url = href

    def handle_endtag(self, tag):
        if tag == "h2" and self._in_tag == "title":
            self.title = "".join(self._current_text).strip()
            self._in_tag = None
        elif tag == "div" and self._in_class == "forum-title":
            self._in_class = None

        elif tag == "div" and self._in_tag == "authors":
            self.author = "".join(self._current_text).strip()
            self._in_tag = None

        elif tag == "span" and self._in_tag == "meta-span":
            text = "".join(self._current_text).strip()
            if re.search(r"\d{4}-\d{2}-\d{2}", text):
                self.date = re.search(r"\d{4}-\d{2}-\d{2}", text).group()
            elif "AOE" in text or re.search(r"\d{2}:\d{2}:\d{2}", text):
                m = re.search(r"(\d{2}:\d{2}:\d{2})", text)
                if m:
                    self.time = m.group(1)
            self._in_tag = None
        elif tag == "div" and self._in_class == "forum-meta":
            self._in_class = None

    def handle_data(self, data):
        if self._in_tag in ("title", "authors", "meta-span"):
            self._current_text.append(data)


# ---------------------------------------------------------------------------
# Fetching & parsing
# ---------------------------------------------------------------------------

def fetch_page(org: str, repo: str) -> str | None:
    """Fetch the GitHub Pages index.html for a review repo."""
    import urllib.request
    url = f"https://{org.lower()}.github.io/{repo}/"
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except Exception:
        return None


def fetch_review_md(org: str, repo: str) -> str:
    """Fetch the review.md from the docs/ directory."""
    import urllib.request
    url = f"https://{org.lower()}.github.io/{repo}/review.md"
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except Exception:
        return ""


def parse_review_md(md_text: str) -> dict:
    """Parse structured Skepthical markdown into sections."""
    sections = {}
    current_key = None
    current_lines = []

    heading_map = {
        "paper summary": "summary",
        "summary": "summary",
        "strengths": "strengths",
        "major issues": "major_issues",
        "minor issues": "minor_issues",
        "very minor issues": "very_minor_issues",
        "key statements and references": "key_statements",
        "key statements": "key_statements",
        "mathematical consistency audit": "maths_audit",
        "mathematics audit": "maths_audit",
        "numerical results audit": "numerics_audit",
        "numerics audit": "numerics_audit",
    }

    for line in md_text.split("\n"):
        m = re.match(r"^#{1,3}\s+(.+)$", line)
        if m:
            heading_text = m.group(1).strip().lower()
            heading_text = re.sub(r"^review:\s*", "", heading_text).rstrip(":")
            matched_key = heading_map.get(heading_text)
            if matched_key:
                if current_key:
                    sections[current_key] = "\n".join(current_lines).strip()
                current_key = matched_key
                current_lines = []
                continue
        if current_key is not None:
            current_lines.append(line)

    if current_key:
        sections[current_key] = "\n".join(current_lines).strip()

    return sections


def parse_page(html: str) -> dict | None:
    """Parse metadata from a review GitHub Pages site."""
    parser = ReviewPageParser()
    parser.feed(html)
    if not parser.title:
        return None

    date = parser.date
    if parser.time:
        date = f"{date} {parser.time}"

    return {
        "paper_title": parser.title,
        "paper_author": parser.author,
        "review_date": date or "",
        "paper_pages_url": parser.paper_pages_url,
    }


_SANITIZE_CACHE: dict[str, str] = {}


def _sanitize_review_math(md_text: str) -> str:
    """Sanitize math notation in review markdown using a cheap LLM.

    Caches results by content hash to avoid repeated API calls on rescrape.
    Returns original text if API key is unavailable or call fails.
    """
    if not md_text or len(md_text) < 100:
        return md_text

    content_hash = hashlib.sha256(md_text.encode()).hexdigest()[:16]
    if content_hash in _SANITIZE_CACHE:
        return _SANITIZE_CACHE[content_hash]

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return md_text

    try:
        from openai import OpenAI

        prompt = (
            "You are a LaTeX math formatter for a scientific peer review document.\n"
            "\n"
            "Your ONLY job: wrap all mathematical expressions in $...$ (inline) or $$...$$ (display) "
            "delimiters with proper LaTeX commands, so KaTeX can render them.\n"
            "\n"
            "Rules:\n"
            "1. Convert Greek Unicode to LaTeX: σ→$\\sigma$, α→$\\alpha$, etc.\n"
            "2. Convert subscripts/superscripts: x_i→$x_i$, σ_norm→$\\sigma_{\\rm norm}$\n"
            "3. Convert operators: ≈→$\\approx$, ≤→$\\leq$, ≥→$\\geq$, ±→$\\pm$, ×→$\\times$, ∼→$\\sim$\n"
            "4. Do NOT wrap: section references, figure references, plain text, issue IDs, URLs, code blocks.\n"
            "5. Do NOT change any wording, structure, or content.\n"
            "6. If text is already in $...$ or $$...$$, leave it.\n"
            "7. Return the COMPLETE document.\n"
            "8. Preserve ALL markdown formatting.\n"
        )

        client = OpenAI(api_key=api_key)
        resp = client.responses.create(
            model="gpt-4.1",
            input=[{"role": "user", "content": [
                {"type": "input_text", "text": prompt + "\n\n=== DOCUMENT ===\n" + md_text},
            ]}],
            timeout=120,
        )

        result = getattr(resp, "output_text", None)
        if not result:
            out = getattr(resp, "output", None)
            if isinstance(out, list):
                for item in out:
                    c = getattr(item, "content", None)
                    if isinstance(c, list):
                        for part in c:
                            t = getattr(part, "text", None)
                            if isinstance(t, str) and t.strip():
                                result = t.strip()
                                break
                    if result:
                        break

        if result and len(result) >= len(md_text) * 0.5:
            _SANITIZE_CACHE[content_hash] = result
            log.info("Math sanitized for scraper (%d → %d chars)", len(md_text), len(result))
            return result
    except Exception as e:
        log.warning("Math sanitization failed in scraper: %s", e)

    return md_text


def _fetch_cost_json(org: str, repo: str) -> float | None:
    """Fetch cost.json from the review repo's Pages site."""
    import urllib.request
    url = f"https://{org.lower()}.github.io/{repo}/cost.json"
    try:
        with urllib.request.urlopen(url, timeout=5) as resp:
            data = json.loads(resp.read())
        cost = data.get("total_cost")
        return float(cost) if cost is not None else None
    except Exception:
        return None


def _fetch_scores_json(org: str, repo: str) -> dict | None:
    """Fetch scores.json from the review repo's Pages site."""
    import urllib.request
    url = f"https://{org.lower()}.github.io/{repo}/scores.json"
    try:
        with urllib.request.urlopen(url, timeout=5) as resp:
            data = json.loads(resp.read())
        if isinstance(data, dict) and "overall" in data:
            return data
        return None
    except Exception:
        return None


def _looks_like_repo_slug(title: str) -> bool:
    """Return True if title looks like a repo slug rather than a real title."""
    # Repo slugs are all lowercase with hyphens and no spaces
    return bool(re.match(r"^[a-z0-9][-a-z0-9]*$", title.strip()))


def _extract_title_from_review_md(md_text: str) -> str:
    """Extract the paper title from the first line of review.md.

    The format is: # **_Skepthical_** review: *Paper Title Here*
    """
    for line in md_text.split("\n"):
        line = line.strip()
        if not line:
            continue
        # Match: # **_Skepthical_** review: *Title*
        m = re.search(r"review:\s*\*(.+?)\*\s*$", line)
        if m:
            return m.group(1).strip()
        break
    return ""


def scrape_single_repo(org: str, repo: str) -> dict | None:
    """Fetch and parse a single review repo. Returns metadata dict or None."""
    html = fetch_page(org, repo)
    if not html:
        return None
    meta = parse_page(html)
    if not meta:
        return None

    # Fetch and parse the review markdown
    review_md = fetch_review_md(org, repo)

    # Sanitize math notation for proper rendering
    review_md = _sanitize_review_math(review_md)

    sections = parse_review_md(review_md)

    # If the HTML title is just a repo slug, try to extract the real title
    # from review.md (first line: # **_Skepthical_** review: *Real Title*)
    if _looks_like_repo_slug(meta["paper_title"]) and review_md:
        md_title = _extract_title_from_review_md(review_md)
        if md_title:
            log.info("Title from review.md for %s: %s", repo, md_title[:80])
            meta["paper_title"] = md_title

    # If the author is unknown/empty, try scraping the paper's own Pages site
    if meta.get("paper_author", "").lower() in ("unknown", ""):
        paper_url = meta.get("paper_pages_url", "")
        if paper_url:
            try:
                import urllib.request
                with urllib.request.urlopen(paper_url, timeout=10) as resp:
                    paper_html = resp.read().decode("utf-8", errors="replace")
                m = re.search(r'Author:\s*</span>\s*(.+?)<', paper_html)
                if not m:
                    m = re.search(r'Author:\s*([^<]+)', paper_html)
                if m:
                    meta["paper_author"] = m.group(1).strip()
                    log.info("Author from paper page for %s: %s", repo, meta["paper_author"])
            except Exception:
                pass

    # Fetch cost.json if available
    total_cost = _fetch_cost_json(org, repo)
    if total_cost is not None:
        meta["total_cost"] = total_cost

    # Fetch scores.json if available
    scores = _fetch_scores_json(org, repo)
    if scores is not None:
        meta["scores"] = scores

    meta["repo"] = repo
    meta["pages_url"] = f"https://{org.lower()}.github.io/{repo}/"
    meta["github_url"] = f"https://github.com/{org}/{repo}"
    meta["review_pdf_source_url"] = f"https://{org.lower()}.github.io/{repo}/review.pdf"
    meta["paper_pdf_source_url"] = f"https://{org.lower()}.github.io/{repo}/paper.pdf"
    meta["sections"] = sections

    return meta


# ---------------------------------------------------------------------------
# Content hashing
# ---------------------------------------------------------------------------

def compute_content_hash(meta: dict) -> str:
    sections = meta.get("sections", {})
    payload = json.dumps({
        "paper_title": meta["paper_title"],
        "paper_author": meta["paper_author"],
        "summary": sections.get("summary", ""),
        "strengths": sections.get("strengths", ""),
        "major_issues": sections.get("major_issues", ""),
    }, sort_keys=True)
    return hashlib.sha256(payload.encode()).hexdigest()


# ---------------------------------------------------------------------------
# PDF handling
# ---------------------------------------------------------------------------

def download_pdf(
    pdf_source_url: str, review_id: str, version: int,
    prefix: str = "review",
    gcs_bucket: str | None = None,
) -> str | None:
    import urllib.request
    try:
        with urllib.request.urlopen(pdf_source_url, timeout=30) as resp:
            pdf_data = resp.read()
    except Exception as exc:
        log.error("PDF download failed for %s: %s", pdf_source_url, exc)
        return None
    if not pdf_data:
        return None

    # Sanitize review_id for filename (replace : and / with _)
    safe_id = review_id.replace(":", "_").replace("/", "_")
    filename = f"{prefix}_{safe_id}v{version}.pdf"

    if gcs_bucket:
        try:
            from google.cloud import storage
            client = storage.Client()
            bucket = client.bucket(gcs_bucket)
            blob = bucket.blob(filename)
            blob.upload_from_string(pdf_data, content_type="application/pdf")
            return f"https://storage.googleapis.com/{gcs_bucket}/{filename}"
        except Exception as exc:
            log.error("GCS PDF upload failed: %s", exc)
    return None


# ---------------------------------------------------------------------------
# Upsert logic
# ---------------------------------------------------------------------------

def upsert_review(
    conn: sqlite3.Connection,
    meta: dict,
    org: str,
    gcs_bucket: str | None = GCS_BUCKET,
    skip_pdf: bool = False,
) -> tuple[str, int, str]:
    """Insert or update a review. Returns (review_id, version, action)."""
    repo = meta["repo"]
    content_hash = compute_content_hash(meta)
    sections = meta.get("sections", {})

    # Derive paper repo from review repo: "review-{paper_repo}" → "{paper_repo}"
    paper_repo = repo[len("review-"):] if repo.startswith("review-") else repo

    review_id = get_or_assign_review_id(conn, paper_repo=paper_repo, review_repo=repo, org=org)

    existing = conn.execute(
        "SELECT version, content_hash FROM reviews "
        "WHERE review_id = ? AND is_current = 1",
        (review_id,),
    ).fetchone()

    if existing and existing["content_hash"] == content_hash:
        # Even if content is unchanged, update scores if they're newly available
        new_scores = meta.get("scores") or {}
        if new_scores.get("overall") is not None:
            current_score = conn.execute(
                "SELECT score_overall FROM reviews WHERE review_id = ? AND is_current = 1",
                (review_id,),
            ).fetchone()
            if current_score and current_score["score_overall"] is None:
                conn.execute(
                    "UPDATE reviews SET score_overall=?, score_soundness=?, score_novelty=?, "
                    "score_significance=?, score_clarity=?, score_evidence=?, score_justification=? "
                    "WHERE review_id=? AND is_current=1",
                    (
                        new_scores.get("overall"),
                        new_scores.get("soundness"),
                        new_scores.get("novelty"),
                        new_scores.get("significance"),
                        new_scores.get("clarity"),
                        new_scores.get("evidence_quality"),
                        new_scores.get("justification", ""),
                        review_id,
                    ),
                )
                conn.commit()
                log.info("SCORES %s (overall=%s)", review_id, new_scores.get("overall"))
                return review_id, existing["version"], "scores_updated"
        return review_id, existing["version"], "unchanged"

    if existing:
        old_version = existing["version"]
        new_version = old_version + 1
        conn.execute(
            "UPDATE reviews SET is_current = 0 WHERE review_id = ? AND version = ?",
            (review_id, old_version),
        )
        action = "updated"
    else:
        new_version = 1
        action = "new"

    review_pdf_url = ""
    paper_pdf_url = ""
    if not skip_pdf:
        review_pdf_url = download_pdf(
            meta["review_pdf_source_url"], review_id, new_version,
            prefix="review", gcs_bucket=gcs_bucket,
        ) or ""
        paper_pdf_url = download_pdf(
            meta["paper_pdf_source_url"], review_id, new_version,
            prefix="paper", gcs_bucket=gcs_bucket,
        ) or ""

    # Extract PX ID from the review_id (e.g. "2604.00003-R1" → "2604.00003")
    px_id = review_id.rsplit("-R", 1)[0] if "-R" in review_id else ""

    scores = meta.get("scores") or {}

    conn.execute(
        "INSERT INTO reviews "
        "(review_id, version, paper_title, paper_author, review_date, "
        " summary, strengths, major_issues, minor_issues, very_minor_issues, "
        " maths_audit, numerics_audit, reviewer, repo, "
        " pages_url, github_url, review_pdf_url, paper_pdf_url, "
        " paper_pages_url, px_id, total_cost, "
        " score_overall, score_soundness, score_novelty, score_significance, "
        " score_clarity, score_evidence, score_justification, "
        " is_current, content_hash) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)",
        (
            review_id, new_version,
            meta["paper_title"], meta["paper_author"], meta["review_date"],
            sections.get("summary", ""),
            sections.get("strengths", ""),
            sections.get("major_issues", ""),
            sections.get("minor_issues", ""),
            sections.get("very_minor_issues", ""),
            sections.get("maths_audit", ""),
            sections.get("numerics_audit", ""),
            "Skepthical",
            repo,
            meta["pages_url"], meta["github_url"],
            review_pdf_url, paper_pdf_url,
            meta.get("paper_pages_url", ""),
            px_id,
            meta.get("total_cost"),
            scores.get("overall"),
            scores.get("soundness"),
            scores.get("novelty"),
            scores.get("significance"),
            scores.get("clarity"),
            scores.get("evidence_quality"),
            scores.get("justification", ""),
            content_hash,
        ),
    )
    conn.commit()

    log.info("%s %s v%d (%s)", action.upper(), review_id, new_version, meta["paper_title"][:60])
    return review_id, new_version, action


# ---------------------------------------------------------------------------
# Bulk scrape
# ---------------------------------------------------------------------------

def _is_duplicate_review_repo(name: str, all_repos: set[str]) -> bool:
    """Detect timestamp-suffixed duplicate review repos.

    E.g., review-act-dr6-crossfreq-coherence-202604081116 is a duplicate
    if review-act-dr6-crossfreq-coherence also exists.
    """
    m = re.match(r"^(review-.+)-(\d{12})$", name)
    if m:
        base = m.group(1)
        return base in all_repos
    return False


def list_review_repos(org: str) -> list[str]:
    """List review repos (prefixed with 'review-') in the org.

    Filters out timestamp-suffixed duplicate repos when the canonical
    review repo (without timestamp) also exists.
    """
    import urllib.request
    repos: list[str] = []
    page = 1
    while True:
        url = f"https://api.github.com/orgs/{org}/repos?per_page=100&page={page}"
        req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
        token = os.environ.get("GITHUB_TOKEN")
        if token:
            req.add_header("Authorization", f"Bearer {token}")
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read())
        if not data:
            break
        repos.extend(r["name"] for r in data if r["name"].startswith("review-"))
        page += 1

    # Filter out timestamp-suffixed duplicates
    repo_set = set(repos)
    filtered = [r for r in repos if not _is_duplicate_review_repo(r, repo_set)]
    if len(filtered) < len(repos):
        log.info("Filtered %d duplicate timestamp-suffixed review repos", len(repos) - len(filtered))
    return filtered


def scrape_all_repos(
    conn: sqlite3.Connection,
    org: str = "ParallelScience",
    skip_pdf: bool = False,
    gcs_bucket: str | None = GCS_BUCKET,
) -> dict[str, int]:
    """Scrape all review repos in the org."""
    repos = list_review_repos(org)
    counts = {"new": 0, "updated": 0, "unchanged": 0, "failed": 0}

    print(f"Found {len(repos)} review repos in {org}")
    for repo in repos:
        print(f"  {repo}...", end=" ", flush=True)
        meta = scrape_single_repo(org, repo)
        if not meta:
            print("skip")
            counts["failed"] += 1
            continue
        try:
            rx_id, version, action = upsert_review(
                conn, meta, org, gcs_bucket=gcs_bucket, skip_pdf=skip_pdf,
            )
            print(f"{action} -> {rx_id} v{version}")
            counts[action] += 1
        except Exception as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            counts["failed"] += 1

    return counts
